Squashed commit of the following:
commit 55a23f01bbbf17f6779c44468ed71b1f1e172205
Author: Iro91 <ivromero19@gmail.com>
Date:   Wed Jan 3 19:30:49 2024 -0800

    Added stow warning

commit 6ad27fe90cd79190cd4502a7472c46745604da12
Author: Iro91 <ivromero19@gmail.com>
Date:   Wed Jan 3 16:44:49 2024 -0800

    Describe installation process

commit 0f171c2c5fd3a389e05d383298af899890f3c0f3
Author: Iro91 <ivromero19@gmail.com>
Date:   Wed Jan 3 16:38:32 2024 -0800

    Do not install npm

commit 3f83021a44a52eaa27f6a77ac1f407a73016ced1
Author: Ivan <ivromero19@gmail.com>
Date:   Wed Jan 3 16:18:11 2024 -0800

    shellcheck script cleanup

commit a431bce22c2f680a41ae04ca96f8630b4911e431
Author: Iro91 <ivromero19@gmail.com>
Date:   Tue Jan 2 15:38:51 2024 -0800

    Added linting

commit d5063aa29ce015f8c1c03d06ec24537ee1340d4f
Author: Ivan <ivromero19@gmail.com>
Date:   Tue Jan 2 08:47:26 2024 -0800

    Added lua lsp

commit 7d6ee5cc864e6ab0bc7de3d8cd9a8dcbb8d9fd04
Author: Ivan <ivromero19@gmail.com>
Date:   Mon Jan 1 23:15:10 2024 -0800

    Added a file exploroer

commit a5caf06e0519fbf4781cd9d381bf22cf993f9db6
Author: Ivan <ivromero19@gmail.com>
Date:   Mon Jan 1 22:46:55 2024 -0800

    Combine lualine and themes

commit b753e33483e0cbbb02f28dd62fa676bba850ca04
Author: Ivan <ivromero19@gmail.com>
Date:   Mon Jan 1 11:29:36 2024 -0800

    Make tmux pretty

commit 10ce4d3bd8e7f6f5eb154603e036af94d3f847f0
Author: Ivan <ivromero19@gmail.com>
Date:   Sun Dec 31 17:29:10 2023 -0800

    prep to setup lsp

commit 0eec8bfde2ee2e53c3655ea59865f0090a1ceb08
Author: Iro91 <ivromero19@gmail.com>
Date:   Sat Dec 30 18:38:53 2023 -0800

    Plugin improvements

commit 3e7e81a5e325896071516210701d553058c35617
Author: Iro91 <ivromero19@gmail.com>
Date:   Sat Dec 30 15:51:39 2023 -0800

    Fix alacritty font. Improved telescope search

commit e7906aa6f0980434e6e9cfaf0af11f041c546085
Author: Ivan <ivromero19@gmail.com>
Date:   Sat Dec 30 15:07:32 2023 -0800

    Added alacritty and i3

commit 5afb2e8c9db9d22434bf40fa03befa1b31193063
Author: Iro91 <ivromero19@gmail.com>
Date:   Fri Dec 29 22:38:01 2023 -0800

    Experimenting with alacritty

commit af78df4820c8544d0cf31671faff7dc518770589
Author: Iro91 <ivromero19@gmail.com>
Date:   Fri Dec 29 17:59:09 2023 -0800

    remove makefile

diff --git a/home/.local/bin/bench_create b/home/.local/bin/bench_create
--- a/home/.local/bin/bench_create
+++ b/home/.local/bin/bench_create
@@ -1,53 +1,61 @@
-#!/bin/bash
-set -e
+#!/bin/bash -e
 
-_USAGE=$(cat << EOF
-General info
-  -h --help:    Prints this usage
-  -v --verbose: Enables script logging
-  -e --edit:    Edit this script
-EOF
-)
-
-THIS_DIR="$( cd "$(dirname "$0")" ; pwd -P )"
-DIR_TEMPLATE="${HOME}/.config/create_bench"
+#-------------------------------------------------------------------------------
 VERBOSE="false"
+DIR_TEMPLATE="${HOME}/.config/create_bench"
+: "${EDITOR:=vim}"
 
-PARAMS=""
-while (( "$#" )); do
-  case "$1" in
-    -h|--help)
-      echo "${_USAGE}"
-      exit 0
-      ;;
-    -v|--verbose)
-      VERBOSE="true"
-      ;;
-    -*|--*=) # unsupported flags
-      echo "Error: Unsupported flag $1" >&2
+#-------------------------------------------------------------------------------
+function Usage() {
+    cat <<EOF
+NAME
+$(basename "$0") Rough Description
+
+DESCRIPTION
+    Detailed description
+    -h  : Print this usage
+    -v  : Enable verbosity
+EOF
+    exit 0
+}
+
+#-------------------------------------------------------------------------------
+function Main() {
+    [[ $VERBOSE == "true" ]] && set -x
+
+    if [ $# -ne 1 ]; then
+      echo "ERROR: Script requires a directory name to create" >&2
       exit 1
-      ;;
-    *) # preserve positional arguments
-      PARAMS="$PARAMS $1"
-      ;;
-  esac
-  shift
+    fi
+
+    local target="${1}"
+    if [ -d "$target" ]; then
+      echo "ERROR: ${1} Already Exists" >&2
+      exit 1
+    fi
+
+    cp -rL "$DIR_TEMPLATE" "${1}"
+    chmod +w "$target"/*
+    echo "${1} Created and prepped for build"
+
+    $EDITOR "${1}/main.cpp"
+}
+
+#-------------------------------------------------------------------------------
+while getopts "hv" opt; do
+    case $opt in
+    h) Usage ;;
+    v) VERBOSE="true" ;;
+    \?)
+        echo "Invalid option: -$OPTARG" >&2
+        exit 1
+        ;;
+    esac
 done
-# set positional arguments in their proper place
-eval set -- "${PARAMS}"
+shift $((OPTIND - 1))
 
-if [ $# -ne 1 ]; then
-  >&2 echo "ERROR: Script requires a directory name to create"
-  exit 1
-fi
 
-if [ -d "${1}" ]; then
-  >&2 echo "ERROR: ${1} Already Exists"
-  exit 1
-fi
+#-------------------------------------------------------------------------------
+Main "${@}"
 
-cp -rL "$DIR_TEMPLATE" "${1}"
-chmod +w ${1}/*
-echo "${1} Created and prepped for build"
 
-gvim "${1}/main.cpp"
